version: '3.8'
# use for local development

services:
  web:
    build: ./services/web
    command: python -m flask run --host=0.0.0.0
    # two-way sync src files between host and container
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - "5000:5000"
    env_file:
      - ./.env.dev